config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Create donations
  resources :donations do
    member do
      get "claim"
    end
  end
  # Create charity organizations
  resources :charities
  # Create content management system pages
  resources :pages

  # Add user authentication routes
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  # View and control background jobs
  mount MissionControl::Jobs::Engine, at: "/background_jobs"

  # In development, send emails to a new tab of the default web browser
  mount LetterOpenerWeb::Engine, at: "/sent_emails" if Rails.env.development?

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#show", id: "home"
end

app/views/partials/_alerts_and_notices.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div role="alert" class="alert alert-error mb-4">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span><%= message %></span>
    </div>
  <% else %>
    <div role="alert" class="alert alert-info mb-4">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="h-6 w-6 shrink-0 stroke-current">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
      </svg>
      <span><%= message %></span>
    </div>
  <% end %>
<% end %>

app/views/partials/_footer.html.erb
<footer class="footer sm:footer-horizontal footer-center bg-base-300 text-base-content p-4 mt-4">
  <aside>
    <p>Copyright © 2025 - Ottawa Helps</p>
  </aside>
</footer>

app/views/partials/_navbar.html.erb
<div class="navbar bg-primary text-primary-content shadow-sm">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /> </svg>
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-primary text-primary-content rounded-box z-1 mt-3 w-52 p-2 shadow">
        <%= render "partials/navbar_links" %>
      </ul>
    </div>
    <a href="<%= root_url %>" class="btn btn-ghost text-xl">Ottawa Helps</a>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      <%= render "partials/navbar_links" %>
    </ul>
  </div>
  <div class="navbar-end">
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
        <div class="relative w-10 h-10 rounded-full overflow-hidden bg-gray-100 dark:bg-gray-600">
          <% if user_signed_in? and current_user.profile_picture.attached? %>
            <%= image_tag current_user.profile_picture, alt: "Profile Picture of #{current_user.username}" %>
          <% else %>
            <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
          <% end %>
        </div>
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-primary text-primary-content rounded-box z-1 mt-3 w-52 p-2 shadow">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/partials/_navbar_links.html.erb
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Browse Donations", donations_path %></li>
<% if current_user and not current_user&.charity.nil? %>
  <li><%= link_to "Donate an Item", new_donation_path %></li>
<% end %>
<li><%= link_to "Browse Charities", charities_path %></li>
<% if current_user %>
  <li><%= link_to "Register a New Charity", new_charity_path %></li>
<% else %>
  <li><%= link_to "Create an Account", new_user_registration_path %></li>
<% end %>