config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Create donations
  resources :donations do
    member do
      get "claim"
    end
  end
  # Create charity organizations
  resources :charities
  # Create content management system pages
  resources :pages

  # Add user authentication routes
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  # View and control background jobs
  mount MissionControl::Jobs::Engine, at: "/background_jobs"

  # In development, send emails to a new tab of the default web browser
  mount LetterOpenerWeb::Engine, at: "/sent_emails" if Rails.env.development?

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#show", id: "home"
end

app/views/pages/_form.html.erb
<%= form_with(model: page, class: "contents") do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul class="list-disc ml-6">
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.textarea :title, rows: 4, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": page.errors[:title].none?, "border-red-400 focus:outline-red-600": page.errors[:title].any? } ] %>
  </div>

  <div class="my-5">
    <%= form.label :subtitle %>
    <%= form.textarea :subtitle, rows: 4, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": page.errors[:subtitle].none?, "border-red-400 focus:outline-red-600": page.errors[:subtitle].any? } ] %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.rich_textarea :body, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": page.errors[:body].none?, "border-red-400 focus:outline-red-600": page.errors[:body].any? } ] %>
  </div>

  <div class="my-5">
    <%= form.label :pictures %>
    <%= form.file_field :pictures, multiple: true, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": page.errors[:pictures].none?, "border-red-400 focus:outline-red-600": page.errors[:pictures].any? } ] %>
  </div>

  <div class="my-5">
    <%= form.label :published_at %>
    <%= form.datetime_field :published_at, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": page.errors[:published_at].none?, "border-red-400 focus:outline-red-600": page.errors[:published_at].any? } ] %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<% if page.title == "Home" %>
  <div class="hero min-h-screen w-full" style="background-image: url(<%= polymorphic_url(page&.pictures&.first) %>);">
    <div class="hero-overlay"></div>
    <div class="hero-content text-neutral-content text-center">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">Ottawa Helps</h1>
        <p class="mb-5">
          "Life’s persistent and most urgent question is, 'What are you doing for others?'"
          - Martin Luther King Jr.
        </p>
      </div>
    </div>
  </div>

  <div class="collapse collapse-arrow bg-base-100 border border-base-300 mt-4">
    <input type="radio" name="my-accordion-2" checked="checked">
    <div class="collapse-title font-semibold">What We Do</div>
    <div class="collapse-content text-sm">Many of our neighbours are fleeing unimaginable violence. In the process, they've lost almost everything. The future seems bleak.

With your help, they can begin to pick up the pieces to start again. One important way is to help them furnish their new home.

Through this website, we connect generous donors with local charities to ensure gently-used household items can find a new home.</div>
  </div>
  <div class="collapse collapse-arrow bg-base-100 border border-base-300">
    <input type="radio" name="my-accordion-2">
    <div class="collapse-title font-semibold">Do you want to donate something?</div>
    <div class="collapse-content text-sm">
      <p>
        We offer gently used household items to individuals and families that might need them. In the process, we value and respect dignity as well as generosity.
      </p>
      <br>
      <p><strong>Accepted Bedroom Items</strong></p>
      <ul>
        <li>Single/twin mattresses in mint condition less than 10 years old; double, queen and king mattresses in mint condition less than 5 years old.
        Photos must be provided for preliminary assessment of acceptance. The ultimate decision to accept mattresses is made at the warehouse.
        All mattresses should be dropped off or ready for collection wrapped in a plastic bag or mattress protector for protection during transportation.
        Mattresses must be completely free of stains.</li>

        <li>Bed Frames – simple assembly</li>
        <li>Bunk bed (simple to assemble)</li>
        <li>Dressers</li>
        <li>Night tables</li>
        <li>Bedroom linens  (bed sheets, blankets and bed spread, including crib linens) - Please indicate size.</li>

        <li>We DO NOT accept: items with missing parts, odd shape beds; foldaway beds; beds/mattresses with stains or tears</li>
      </ul>
      <br>
      <p><strong>Accepted Living Room Items</strong></p>
      <ul>
        <li>Sofas and loveseats (under width 7’)</li>
        <li>Living room armchairs</li>
        <li>End tables</li>
        <li>Coffee tables (if square no larger than 3’ X 3’)</li>
        <li>Lamps</li>

        <li>We DO NOT accept: TV units, wall units, or entertainment units; sofas over width 7’,odd living room chairs; ceiling light fixtures or hanging light fixtures; large china cabinets</li>
      </li>
      <br>
      <p><strong>Accepted Kitchen and Dining Items</strong><p>
      <ul>
        <li>Kitchen and dining room tables (under width 5' with leaf out)</li>
        <li>Kitchen and dining room chairs (only sets of 2 chairs or more)</li>
        <li>Microwave stands</li>
        <li>Dishes, glasses, kitchen utensils, cookware</li>
        <li>Kitchen linens</li>
        <li>Small kitchen appliances</li>

        <li>We DO NOT accept: stools; large dining room sets; dishware with chips, cracks and badly scratched; plastic dishware (except for children dishes)</li>
      </ul>
      <br>
      <p><strong>Accepted Bathroom Items</strong></p>
      <ul>
        <li>Bathroom items (towels, shower curtains, bath mat)</li>
        <li>We DO NOT accept: Any items that are stained and not in good condition</li>
      </ul>
      <br>
      <p><strong>Accepted Children Items</strong></p>
      <ul>
        <li>Kids books all languages</li>
        <li>Toys (clean, not battery operated or with brand new batteries) & complete sets)</li>
        <li>Baby equipment (strollers, baby seats, toys)</li>
        <li>Change tables</li>

        <li>We DO NOT accept: car seats</li>
      </ul>
      <br>
      <p><strong>Accepted Office Furniture</strong></p>
      <ul>
        <li>Desks (under width 3’ and depth 20”)</li>
        <li>Desk lamps</li>
        <li>Office chairs</li>
        <li>Bookshelves (under width 3’ and shelf depth 14”)</li>

        <li>We DO NOT accept: large or L shape desks; hanging bookcases; bookcases requiring complicated assembly; any unit taller than 6’ and over width 3’; printer tables; office furniture items that are oversized or excessively heavy</li>
      </ul>
      <br>
      <p><strong>Accepted Electric and Electronic Items</strong></p>
      <ul>
        <li>Laptops less than 5 yrs old</li>
        <li>Flat screen TVs</li>
        <li>Microwaves</li>
        <li>Clock radios</li>
        <li>Laser printers</li>
        <li>Recent smartphones</li>
        <li>Recent tablets</li>

        <li>We do not accept: stereos, speakers, VCR players, inkjet printers and telephones; console, floor model and tube style TVs; large appliances like stoves, fridges, dishwashers, washers & dryers</li>
      </ul>
      <br>
      <p><strong>Accepted Miscellaneous Household Items</strong></p>
      <ul>
        <li>Irons and ironing boards</li>
        <li>Garbage cans</li>
        <li>Laundry baskets</li>
        <li>Clothes dryers</li>
        <li>Shopping carts</li>
        <li>Vacuum cleaners</li>
        <li>Framed Artwork</li>
        <li>Area rugs (no larger than 10' X 8')</li>
        <li>Entrance mat, bedside mat, boot tray</li>
        <li>Shoe rack</li>
        <li>Fans</li>
        <li>Rod pocket curtains and pocket curtains rods</li>
        <li>Outdoor furniture (table for 4 or 2 persons, lawn chairs)</li>
        <li>Tools (drills, hammers, etc)</li>

        <li>We DO NOT accept: BBQ; bathroom medicine cabinets or bathroom shelving that requires hanging; blinds or curtain rods with cords</li>
      </ul>
    </div>
  </div>
  <div class="collapse collapse-arrow bg-base-100 border border-base-300">
    <input type="radio" name="my-accordion-2">
    <div class="collapse-title font-semibold">Does your charity need something?</div>
    <div class="collapse-content text-sm">As a registered charity, your work is the cornerstone of helping others.

Please tell us a little about the work you do. Be sure to include your Canadian Charity registration number and contact information.</div>
  </div>
  <div class="collapse collapse-arrow bg-base-100 border border-base-300">
    <input type="radio" name="my-accordion-2">
    <div class="collapse-title font-semibold">Frequently Asked Questions</div>
    <div class="collapse-content text-sm">
      <p><strong>How do I get in touch with you to give furniture?</strong><p>
      <p>After verifying the items we take and don’t take, you can drop them off at our warehouse, 1455 Michael Street, Unit 3 in Ottawa, Wednesdays from 6 pm to 9 pm and Saturdays 10 am to 1 pm. You no longer need an appointment. You can also fill out a Request for Pickup by HWF Truck. Please make sure to book reasonably in advance. We do book quickly.</p>
      <br>
      <p><strong>Do you charge for furniture pickups?</strong></p>
      <p>Yes. When you complete a Request for Pickup by HWF Truck, you’ll see a breakdown of the pickup rates.</p>
      <br>
      <p><strong>What items will you take and not take?</strong></p>
      <p>Please refer to our list of items that we accept and don’t accept. We do not accept extra large or heavy items, soft furniture used by animals or smokers, torn or unclean soft furniture. We reserve the right to refuse items that do not meet our standards of condition. Our volunteers have the authority to make this final decision when you drop off your furniture.</p>
      <br>
      <p><strong>Do I have to prepare items for drop off?</strong></p>
      <p>Furniture must be clean and of a quality that we would take in our own homes. Dishes, linens and small items must be boxed or packed, identified as to contents. Loose pieces of related items (e.g. nuts, bolts, screws of beds, tables with legs, TV’s with remotes) must be tied or taped together.</p>
      <br>
      <p><strong>Do you take mattresses?</strong></p>
      <p>Yes. They must be in good condition, unstained, no rips. If possible, in a plastic bag.</p>
      <br>
      <p><strong>Who can I contact if I have items you don’t take?</strong></p>
      <p>The City of Ottawa provides a list of places that will take used items. You can reach them here. </p>
  </div>
  </div>

<% else %>
  <div id="<%= dom_id page %>" class="w-full sm:w-auto my-5 space-y-5">
    <div class="text-4xl">
      <%= page.title %>
    </div>
    <div class="text-2xl">
      <%= page.subtitle %>
    </div>
    <div class="prose-xl">
      <%= page.body %>
    </div>
  </div>
<% end %>

app/views/pages/edit.html.erb
<% content_for :title, "Editing page" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing page</h1>

  <%= render "form", page: @page %>

  <%= link_to "Show this page", @page, class: "btn btn-secondary" %>
  <%= link_to "Back", :back, class: "btn btn-accent" %>
</div>

app/views/pages/index.html.erb
<% content_for :title, "Pages" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Pages</h1>
    <% if current_user %>
      <%= link_to "New page", new_page_path, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div id="pages" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @pages.any? %>
      <% @pages.each do |page| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render page %>
          <% if page.user == current_user %>
            <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
              <%= link_to "Show", page, class: "btn btn-primary" %>
              <%= link_to "Edit", edit_page_path(page), class: "btn btn-secondary" %>
              <%= button_to "Delete", page, method: :delete, class: "btn btn-error", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No pages found.</p>
    <% end %>
  </div>
</div>

app/views/pages/new.html.erb
<% content_for :title, "New page" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New page</h1>

  <%= render "form", page: @page %>

  <%= link_to "Back", :back, class: "btn btn-secondary" %>
</div>

app/views/pages/show.html.erb
<% content_for :title, "Showing page" %>

<% if @page.title == 'Home' %>
  <%= render @page %>
<% else %>
<div class="md:w-2/3 w-full">
  <%= render @page %>

  <%= link_to "Back", :back, class: "btn btn-secondary" %>
  <% if @page.user == current_user %>
    <%= link_to "Edit this page", edit_page_path(@page), class: "btn btn-primary" %>
    <%= button_to "Delete this page", @page, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "btn btn-error", data: { turbo_confirm: "Are you sure?" } %>
  <% end %>
</div>
<% end %>