config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Create donations
  resources :donations do
    member do
      get "claim"
    end
  end
  # Create charity organizations
  resources :charities
  # Create content management system pages
  resources :pages

  # Add user authentication routes
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  # View and control background jobs
  mount MissionControl::Jobs::Engine, at: "/background_jobs"

  # In development, send emails to a new tab of the default web browser
  mount LetterOpenerWeb::Engine, at: "/sent_emails" if Rails.env.development?

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#show", id: "home"
end

app/models/donation.rb
# == Schema Information
#
# Table name: donations
#
#  id            :uuid             not null, primary key
#  archived_at   :datetime
#  category      :text             not null
#  claimed_at    :datetime
#  condition     :text
#  name          :text             not null
#  quantity      :integer          not null
#  slug          :text             not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  claimed_by_id :uuid
#  user_id       :uuid
#
# Indexes
#
#  index_donations_on_claimed_by_id  (claimed_by_id)
#  index_donations_on_slug           (slug) UNIQUE
#  index_donations_on_user_id        (user_id)
#
# Foreign Keys
#
#  fk_rails_6aeba1396a  (claimed_by_id => charities.id)
#
class Donation < ApplicationRecord
  self.implicit_order_column = "created_at"

  has_rich_text :description
  has_many_attached :pictures
  belongs_to :user
  belongs_to :claimed_by, class_name: "Charity", foreign_key: :claimed_by_id, optional: true

  validates :name, :quantity, presence: true

  # Track and store changes to donations
  has_paper_trail

  # Display donations by their name
  extend FriendlyId
  friendly_id :name

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: %i[ show edit update destroy claim ]

  # GET /donations or /donations.json
  def index
    @donations = Donation.where(claimed_by: nil)

    if current_user&.charity
      @claimed_donations = current_user.charity.donations
    end
  end

  # GET /donations/1 or /donations/1.json
  def show
    # If the user uses an old donation URL, redirect to the latest URL and show a flash alert
    if request.path != donation_path(@donation)
      flash.alert = "The donation once at #{request.url} has been updated, and is now located at \
          #{donation_url(@donation)}. You have been redirected."
      redirect_to @donation, status: :moved_permanently and return
    end
  end

  # GET /donations/new
  def new
    authenticate_user!

    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
    authenticate_user!

    # If the user uses an old edit donation URL, redirect to the latest URL and show a flash alert
    if request.path != edit_donation_path(@donation)
      flash.alert = "The donation once at #{request.url} has been updated, and is now located at \
          #{edit_donation_url(@donation)}. You have been redirected."
      redirect_to edit_donation_path(@donation), status: :moved_permanently and return
    end
  end

  # POST /donations or /donations.json
  def create
    authenticate_user!

    @donation = Donation.new(donation_params)
    @donation.user = current_user

    respond_to do |format|
      if @donation.save
        # Send a notification to each charity that has the donation's category matching one of their needs
        Charity.all.each do |charity|
          if charity.needs.include?(@donation.category)
            DonationMailer.with(charity: charity, donation: @donation).notify_charity.deliver_now
          end
        end

        format.html { redirect_to @donation, notice: "Donation was successfully created." }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1 or /donations/1.json
  def update
    authenticate_user!

    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: "Donation was successfully updated." }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1 or /donations/1.json
  def destroy
    authenticate_user!

    @donation.destroy!

    respond_to do |format|
      format.html { redirect_to donations_path, status: :see_other, notice: "Donation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /donations/1/claim
  def claim
    authenticate_user!

    if current_user.charity.nil?
      flash.alert = "Only registered charities can claim a donation."
      redirect_back fallback_location: donations_path and return
    end

    @donation.claimed_at = DateTime.now
    @donation.claimed_by = current_user.charity
    @donation.save!

    redirect_to @donation, status: :found, notice: "You have claimed this donation. Please contact the donator to arrange transportation."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.friendly.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def donation_params
      params.expect(donation: [ :name, :category, :quantity, :description, :condition, pictures: [] ])
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<div id="<%= dom_id donation %>" class="w-full sm:w-auto my-5 space-y-5">
  <% if donation.name? %>
    <div class="block">
      <strong class="font-medium mb-1">Name of the Donation:</strong>
      <%= donation.name %>
    </div>
  <% end %>
  <% if donation.category? %>
    <div class="block">
      <strong class="font-medium mb-1">Category:</strong>
      <%= donation.category %>
    </div>
  <% end %>
  <% if donation.quantity? %>
    <div class="block">
      <strong class="font-medium mb-1">Quantity:</strong>
      <%= donation.quantity %>
    </div>
  <% end %>
  <% unless donation.user.nil? %>
    <div class="block">
      <strong class="font-medium mb-1">Donated By:</strong>
      <%= donation.user.name %>
    </div>
  <% end %>
  <% if donation.condition? %>
    <div class="block">
      <strong class="font-medium mb-1">Condition:</strong>
      <%= donation.condition %>
    </div>
  <% end %>
  <% if donation.description? %>
    <div>
      <strong class="block font-medium mb-1">Description:</strong>
      <%= donation.description %>
    </div>
  <% end %>
  <% if donation.pictures.attached? %>
    <div>
      <strong class="block font-medium mb-1">Pictures:</strong>
      <% donation.pictures.each do |picture| %>
        <div><%= link_to picture.filename, picture, class: "text-gray-700 underline hover:no-underline" %></div>
      <% end %>
    </div>
  <% end %>
  <% if donation.claimed_at? %>
    <div class="block">
      <strong class="font-medium mb-1">Claimed At:</strong>
      <%= donation.claimed_at %>
    </div>
  <% end %>
  <% if donation.claimed_by %>
    <div class="block">
      <strong class="font-medium mb-1">Claimed By:</strong>
      <%= link_to donation.claimed_by.name.to_s, donation.claimed_by, class: "text-gray-700 underline hover:no-underline" %>
    </div>
  <% end %>
</div>

app/views/donations/_form.html.erb
<%= form_with(model: donation, class: "contents") do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul class="list-disc ml-6">
        <% donation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, "Name of the Donation" %>
    <%= form.textarea :name, rows: 4, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": donation.errors[:name].none?, "border-red-400 focus:outline-red-600": donation.errors[:name].any? } ] %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.select :category, options_for_select(donation_categories, selected: donation.category, disabled: donation_categories_headings) %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": donation.errors[:quantity].none?, "border-red-400 focus:outline-red-600": donation.errors[:quantity].any? } ] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_textarea :description, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": donation.errors[:description].none?, "border-red-400 focus:outline-red-600": donation.errors[:description].any? } ] %>
  </div>

  <div class="my-5">
    <%= form.label :condition %>
    <%= form.textarea :condition, rows: 4, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": donation.errors[:condition].none?, "border-red-400 focus:outline-red-600": donation.errors[:condition].any? } ] %>
  </div>

  <div class="my-5">
    <%= form.label :pictures %>
    <%= form.file_field :pictures, multiple: true, class: [ "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": donation.errors[:pictures].none?, "border-red-400 focus:outline-red-600": donation.errors[:pictures].any? } ] %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<% content_for :title, "Editing Donation" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing Donation</h1>

  <%= render "form", donation: @donation %>

  <%= link_to "Back", :back, class: "btn btn-secondary" %>
</div>

app/views/donations/index.html.erb
<% content_for :title, "Browsing Donations" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Browsing Available Donations</h1>
    <% unless current_user.nil? %>
      <%= link_to "Add a New Donation", new_donation_path, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div id="donations" class="min-w-full divide-y divide-gray-400 space-y-5">
    <% if @donations.any? %>
      <% @donations.each do |donation| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render donation %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", donation, class: "btn btn-primary" %>
            <% if current_user and not current_user&.charity.nil? %>
              <%= link_to "Claim", claim_donation_path(donation), class: "btn btn-secondary", data: { turbo_confirm: "Are you sure you want to claim this donation?" } %>
            <% end %>
            <% if current_user and donation.user == current_user %>
              <%= link_to "Edit", edit_donation_path(donation), class: "btn btn-outline btn-secondary" %>
              <%= button_to "Remove", donation, method: :delete, class: "btn btn-error", data: { turbo_confirm: "Are you sure you want to remove this donation?" } %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No donations found.</p>
    <% end %>
  </div>

  <% if current_user&.charity %>
    <h1 class="font-bold text-4xl">Your Charity's Claimed Donations</h1>

    <div id="claimed_donations" class="min-w-full divide-y divide-gray-400 space-y-5">
      <% if @claimed_donations.any? %>
        <% @claimed_donations.each do |donation| %>
          <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
            <%= render donation %>
            <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
              <%= link_to "Show", donation, class: "btn btn-primary" %>
              <% if current_user and donation.user == current_user %>
                <%= link_to "Edit", edit_donation_path(donation), class: "btn btn-outline btn-secondary" %>
                <%= button_to "Remove", donation, method: :delete, class: "btn btn-error", data: { turbo_confirm: "Are you sure you want to remove this donation?" } %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="text-center my-10">No claimed donations found.</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/donations/new.html.erb
<% content_for :title, "New Donation" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Donation</h1>

  <%= render "form", donation: @donation %>

  <%= link_to "Back", :back, class: "btn btn-secondary" %>
</div>

app/views/donations/show.html.erb
<% content_for :title, "Showing Donation" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing Donation</h1>

  <%= render @donation %>

  <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
    <%= link_to "Back", :back, class: "btn btn-primary" %>

    <% if current_user and not current_user&.charity.nil? and @donation.claimed_by.nil? %>
      <%= link_to "Claim", claim_donation_path(@donation), class: "btn btn-secondary", data: { turbo_confirm: "Are you sure you want to claim this donation?" } %>
    <% end %>

    <% if current_user and @donation.user == current_user %>
      <%= link_to "Edit", edit_donation_path(@donation), class: "btn btn-outline btn-secondary" %>
      <%= button_to "Remove", @donation, method: :delete, class: "btn btn-error", data: { turbo_confirm: "Are you sure you want to remove this donation?" } %>
    <% end %>
  </div>
</div>